import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { Pressable,StyleSheet,Text,View } from "react-native";
import { Screen } from "../../src/components/Screen";
import { radii,spacing,typography } from "../../src/design/tokens";
import { mostRecentIncomplete } from "../../src/documents/insights";
import { useDocumentLibrary } from "../../src/documents/DocumentLibraryProvider";
import { useVoticTheme } from "../../src/theme/ThemeProvider";

export default function Home(){
  const {theme}=useVoticTheme(); const {documents,openDocument}=useDocumentLibrary();
  const recent=mostRecentIncomplete(documents); const visible=documents.slice(0,3);
  function open(id:string){openDocument(id);router.push("/reader");}
  return <Screen title="Home" hideTitle>
    <View style={[s.hero,{backgroundColor:theme.surfaceMuted}]}><View style={s.heroCopy}><Text style={[s.welcome,{color:theme.mutedText}]}>Welcome back</Text><Text style={[s.heroTitle,{color:theme.text}]}>Ready to read?</Text><Text style={[s.heroBody,{color:theme.mutedText}]}>Upload a document or pick up where you left off.</Text></View><View style={[s.heroArt,{backgroundColor:theme.sentenceHighlight}]}><Ionicons name="document-text" size={44} color={theme.accent}/></View><Pressable onPress={()=>router.push("/documents")} style={[s.upload,{backgroundColor:theme.accent}]}><Ionicons name="add" size={22} color="#FFF"/><Text style={s.uploadText}>Upload Document</Text></Pressable></View>
    <SectionHeader title="Continue Reading" onPress={()=>router.push("/documents")}/>
    {recent?<Pressable onPress={()=>open(recent.id)} style={[s.continueCard,{backgroundColor:theme.surface,borderColor:theme.border}]}><DocumentIcon title={recent.title}/><View style={s.flex}><Text numberOfLines={1} style={[s.docTitle,{color:theme.text}]}>{recent.title}</Text><Text style={[s.meta,{color:theme.mutedText}]}>{recent.sentenceIndex+1} passages · {Math.round(recent.progress*100)}% read</Text><View style={[s.track,{backgroundColor:theme.border}]}><View style={[s.progress,{backgroundColor:theme.accent,width:`${recent.progress*100}%` as `${number}%`}]}/></View></View><View style={[s.play,{backgroundColor:theme.accent}]}><Ionicons name="play" size={20} color="#FFF"/></View></Pressable>:<Pressable onPress={()=>router.push("/documents")} style={[s.emptyCard,{borderColor:theme.border}]}><Ionicons name="add-circle-outline" size={25} color={theme.accent}/><Text style={[s.emptyText,{color:theme.text}]}>Choose your first document</Text></Pressable>}
    <SectionHeader title="My Documents" onPress={()=>router.push("/documents")}/>
    <View style={[s.documentList,{backgroundColor:theme.surface,borderColor:theme.border}]}>{visible.length?visible.map((doc,i)=><Pressable key={doc.id} onPress={()=>open(doc.id)} style={[s.documentRow,i<visible.length-1&&{borderBottomColor:theme.border,borderBottomWidth:1}]}><DocumentIcon title={doc.title}/><View style={s.flex}><Text numberOfLines={1} style={[s.docTitle,{color:theme.text}]}>{doc.title}</Text><Text style={[s.meta,{color:theme.mutedText}]}>{doc.progress?`${Math.round(doc.progress*100)}% read`:"Ready to read"}</Text></View><Ionicons name="ellipsis-horizontal" size={20} color={theme.mutedText}/></Pressable>):<Text style={[s.noDocs,{color:theme.mutedText}]}>Your recent documents will appear here.</Text>}</View>
    <Text style={[s.sectionTitle,{color:theme.text}]}>Quick Actions</Text><View style={s.quickRow}><QuickAction icon="book-outline" label="Reader" caption="Read and listen" color="#4F46E5" onPress={()=>recent?open(recent.id):router.push("/documents")}/><QuickAction icon="chatbubble-ellipses-outline" label="Ask Votic" caption="Get answers" color="#2563EB" onPress={()=>router.push("/ask")}/><QuickAction icon="document-text-outline" label="Notes" caption="View your notes" color="#D97706" onPress={()=>router.push("/notes")}/></View>
  </Screen>;
}
function SectionHeader({title,onPress}:{title:string;onPress:()=>void}){const {theme}=useVoticTheme();return <View style={s.sectionHeader}><Text style={[s.sectionTitle,{color:theme.text}]}>{title}</Text><Pressable onPress={onPress}><Text style={[s.action,{color:theme.accent}]}>See All</Text></Pressable></View>;}
function DocumentIcon({title}:{title:string}){const lower=title.toLowerCase();const color=lower.endsWith(".pdf")?"#EF4444":lower.endsWith(".epub")?"#10B981":lower.includes("ppt")?"#F97316":"#3B82F6";return <View style={[s.docIcon,{backgroundColor:color+"18"}]}><Ionicons name="document-text-outline" size={24} color={color}/></View>;}
function QuickAction({icon,label,caption,color,onPress}:{icon:React.ComponentProps<typeof Ionicons>["name"];label:string;caption:string;color:string;onPress:()=>void}){return <Pressable onPress={onPress} style={[s.quick,{backgroundColor:color+"10"}]}><Ionicons name={icon} size={30} color={color}/><Text style={s.quickLabel}>{label}</Text><Text style={s.quickCaption}>{caption}</Text></Pressable>;}
const s=StyleSheet.create({hero:{borderRadius:radii.lg,padding:spacing.lg,flexDirection:"row",flexWrap:"wrap",gap:spacing.md},heroCopy:{flex:1,minWidth:190},welcome:{fontSize:13},heroTitle:{fontSize:25,fontWeight:"900",letterSpacing:-.6,marginTop:2},heroBody:{fontSize:14,lineHeight:20,marginTop:4},heroArt:{width:64,height:72,borderRadius:14,alignItems:"center",justifyContent:"center",transform:[{rotate:"-4deg"}]},upload:{width:"100%",minHeight:48,borderRadius:12,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:8},uploadText:{color:"#FFF",fontSize:16,fontWeight:"800"},sectionHeader:{flexDirection:"row",alignItems:"center",justifyContent:"space-between",marginTop:4},sectionTitle:{...typography.sectionTitle,fontSize:18},action:{fontSize:13,fontWeight:"800"},continueCard:{minHeight:82,borderWidth:1,borderRadius:radii.md,padding:10,flexDirection:"row",alignItems:"center",gap:12},emptyCard:{minHeight:72,borderWidth:1,borderRadius:radii.md,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:10},emptyText:{fontWeight:"700"},docIcon:{width:46,height:46,borderRadius:10,alignItems:"center",justifyContent:"center"},flex:{flex:1},docTitle:{fontSize:14,fontWeight:"800"},meta:{fontSize:12,marginTop:4},track:{height:4,borderRadius:2,overflow:"hidden",marginTop:8},progress:{height:"100%"},play:{width:38,height:38,borderRadius:19,alignItems:"center",justifyContent:"center"},documentList:{borderWidth:1,borderRadius:radii.md,overflow:"hidden"},documentRow:{minHeight:70,padding:10,flexDirection:"row",alignItems:"center",gap:12},noDocs:{padding:20,textAlign:"center",fontSize:14},quickRow:{flexDirection:"row",gap:8},quick:{flex:1,minHeight:112,borderRadius:14,padding:10,alignItems:"center",justifyContent:"center"},quickLabel:{fontSize:13,fontWeight:"800",color:"#111827",marginTop:7,textAlign:"center"},quickCaption:{fontSize:10,color:"#6B7280",marginTop:2,textAlign:"center"}});
