import { Ionicons } from "@expo/vector-icons";
import { useState } from "react";
import { Alert,Modal,Pressable,ScrollView,StyleSheet,Switch,Text,TextInput,View } from "react-native";
import { Screen } from "../../src/components/Screen";
import { controlSizes,radii,spacing,typography } from "../../src/design/tokens";
import { useDocumentLibrary } from "../../src/documents/DocumentLibraryProvider";
import { useRoutines } from "../../src/routines/RoutineProvider";
import { ReadingRoutine } from "../../src/routines/types";
import { useVoticTheme } from "../../src/theme/ThemeProvider";

const DAYS=[{value:1,label:"M"},{value:2,label:"T"},{value:3,label:"W"},{value:4,label:"T"},{value:5,label:"F"},{value:6,label:"S"},{value:0,label:"S"}];
const TIMES=[{value:"08:00",label:"Morning",detail:"8:00 AM"},{value:"13:00",label:"Afternoon",detail:"1:00 PM"},{value:"19:00",label:"Evening",detail:"7:00 PM"},{value:"21:00",label:"Night",detail:"9:00 PM"}];
type Editor={id:string;name:string;days:number[];time:string;documentId?:string;enabled:boolean};
function blank():Editor{return {id:"routine-"+Date.now()+"-"+Math.random().toString(36).slice(2,7),name:"Reading time",days:[1,2,3,4,5],time:"19:00",enabled:true};}
function friendlyTime(value:string){const [rawHour,minute]=value.split(":").map(Number);const suffix=rawHour>=12?"PM":"AM";const hour=rawHour%12||12;return `${hour}:${String(minute).padStart(2,"0")} ${suffix}`;}
function daySummary(days:number[]){if(days.length===7)return "Every day";if(days.length===5&&[1,2,3,4,5].every(day=>days.includes(day)))return "Weekdays";return DAYS.filter(day=>days.includes(day.value)).map(day=>day.label).join(" · ");}

export default function Routines(){
  const {theme}=useVoticTheme();const {documents}=useDocumentLibrary();const {routines,saveRoutine,setRoutineEnabled,removeRoutine}=useRoutines();
  const [editor,setEditor]=useState<Editor|null>(null);const [saving,setSaving]=useState(false);
  function edit(routine:ReadingRoutine){setEditor({id:routine.id,name:routine.name,days:routine.days,time:routine.time,documentId:routine.documentId,enabled:routine.enabled});}
  function documentTitle(id?:string){return documents.find(document=>document.id===id)?.title;}
  async function save(){if(!editor||!editor.name.trim()||!editor.days.length)return;setSaving(true);try{await saveRoutine({...editor,name:editor.name.trim()},documentTitle(editor.documentId));setEditor(null);}catch(error){Alert.alert("Reminder not enabled",error instanceof Error?error.message:"Votic could not schedule this reminder.");}finally{setSaving(false);}}
  async function toggle(routine:ReadingRoutine,value:boolean){try{await setRoutineEnabled(routine.id,value,documentTitle(routine.documentId));}catch(error){Alert.alert("Reminder not enabled",error instanceof Error?error.message:"Votic could not update this reminder.");}}
  function remove(){if(!editor)return;Alert.alert("Delete this routine?","Its scheduled reminders will also be removed.",[{text:"Keep routine",style:"cancel"},{text:"Delete",style:"destructive",onPress:()=>{void removeRoutine(editor.id);setEditor(null);}}]);}
  function toggleDay(day:number){if(!editor)return;setEditor({...editor,days:editor.days.includes(day)?editor.days.filter(value=>value!==day):[...editor.days,day].sort()});}

  return <Screen title="Routines">
    <View style={s.intro}><Text style={[s.heading,{color:theme.text}]}>Make space for reading</Text><Text style={[s.body,{color:theme.mutedText}]}>Choose when you intend to read. Reminders are optional, specific, and scheduled only on this device.</Text></View>
    <Pressable accessibilityRole="button" accessibilityLabel="Create reading routine" onPress={()=>setEditor(blank())} style={({pressed})=>[s.add,{backgroundColor:theme.accent,opacity:pressed?.78:1}]}><Ionicons name="add" size={21} color="#FFF"/><Text style={s.addText}>New routine</Text></Pressable>
    {routines.length?<View style={s.list}>{[...routines].sort((a,b)=>a.time.localeCompare(b.time)).map(routine=><Pressable key={routine.id} accessibilityRole="button" accessibilityLabel={`Edit ${routine.name}`} onPress={()=>edit(routine)} style={({pressed})=>[s.card,{borderColor:theme.border,backgroundColor:pressed?theme.surfaceMuted:theme.surface}]}><View style={[s.timeIcon,{backgroundColor:theme.sentenceHighlight}]}><Ionicons name="time-outline" size={24} color={theme.accent}/></View><View style={s.cardCopy}><Text style={[s.cardTitle,{color:theme.text}]}>{routine.name}</Text><Text style={[s.cardMeta,{color:theme.mutedText}]}>{daySummary(routine.days)} · {friendlyTime(routine.time)}</Text><Text numberOfLines={1} style={[s.cardDocument,{color:theme.mutedText}]}>{documentTitle(routine.documentId)||"Any document"}</Text></View><Switch accessibilityLabel={`${routine.name} reminder`} value={routine.enabled} onValueChange={value=>void toggle(routine,value)} trackColor={{true:theme.accent}}/></Pressable>)}</View>:<View style={s.empty}><Ionicons name="notifications-outline" size={32} color={theme.mutedText}/><Text style={[s.emptyTitle,{color:theme.text}]}>No routines yet</Text><Text style={[s.emptyBody,{color:theme.mutedText}]}>A routine can be as simple as ten quiet minutes after dinner.</Text></View>}

    <Modal visible={editor!==null} transparent animationType="slide" onRequestClose={()=>setEditor(null)}><View style={s.backdrop}><View accessibilityViewIsModal style={[s.sheet,{backgroundColor:theme.surface}]}><View style={[s.handle,{backgroundColor:theme.border}]}/><View style={s.sheetHeader}><Text accessibilityRole="header" style={[s.sheetTitle,{color:theme.text}]}>{routines.some(routine=>routine.id===editor?.id)?"Edit routine":"New routine"}</Text><Pressable accessibilityRole="button" accessibilityLabel="Close routine editor" onPress={()=>setEditor(null)} style={s.close}><Ionicons name="close" size={24} color={theme.text}/></Pressable></View>{editor?<ScrollView showsVerticalScrollIndicator={false} keyboardShouldPersistTaps="handled" contentContainerStyle={s.editorContent}>
      <Text style={[s.label,{color:theme.mutedText}]}>NAME</Text><TextInput accessibilityLabel="Routine name" value={editor.name} onChangeText={name=>setEditor({...editor,name})} maxLength={40} placeholder="Reading time" placeholderTextColor={theme.mutedText} style={[s.input,{borderColor:theme.border,color:theme.text,backgroundColor:theme.background}]}/>
      <Text style={[s.label,{color:theme.mutedText}]}>DAYS</Text><View style={s.days}>{DAYS.map(day=>{const active=editor.days.includes(day.value);return <Pressable key={day.value} accessibilityRole="checkbox" accessibilityState={{checked:active}} accessibilityLabel={["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"][day.value]} onPress={()=>toggleDay(day.value)} style={[s.day,{borderColor:active?theme.accent:theme.border,backgroundColor:active?theme.sentenceHighlight:theme.surface}]}><Text style={[s.dayText,{color:active?theme.accent:theme.text}]}>{day.label}</Text></Pressable>;})}</View>
      <Text style={[s.label,{color:theme.mutedText}]}>TIME</Text><View style={s.options}>{TIMES.map(time=>{const active=editor.time===time.value;return <Pressable key={time.value} accessibilityRole="radio" accessibilityState={{checked:active}} onPress={()=>setEditor({...editor,time:time.value})} style={[s.option,{borderColor:active?theme.accent:theme.border,backgroundColor:active?theme.sentenceHighlight:theme.surface}]}><Text style={[s.optionTitle,{color:active?theme.accent:theme.text}]}>{time.label}</Text><Text style={[s.optionDetail,{color:theme.mutedText}]}>{time.detail}</Text></Pressable>;})}</View>
      <Text style={[s.label,{color:theme.mutedText}]}>DOCUMENT</Text><View style={s.documentOptions}><Pressable accessibilityRole="radio" accessibilityState={{checked:!editor.documentId}} onPress={()=>setEditor({...editor,documentId:undefined})} style={[s.documentOption,{borderColor:!editor.documentId?theme.accent:theme.border}]}><Text style={[s.documentOptionText,{color:theme.text}]}>Any document</Text>{!editor.documentId?<Ionicons name="checkmark" size={18} color={theme.accent}/>:null}</Pressable>{documents.slice(0,4).map(document=><Pressable key={document.id} accessibilityRole="radio" accessibilityState={{checked:editor.documentId===document.id}} onPress={()=>setEditor({...editor,documentId:document.id})} style={[s.documentOption,{borderColor:editor.documentId===document.id?theme.accent:theme.border}]}><Text numberOfLines={1} style={[s.documentOptionText,{color:theme.text}]}>{document.title}</Text>{editor.documentId===document.id?<Ionicons name="checkmark" size={18} color={theme.accent}/>:null}</Pressable>)}</View>
      <View style={s.actions}>{routines.some(routine=>routine.id===editor.id)?<Pressable accessibilityRole="button" accessibilityLabel="Delete routine" onPress={remove} style={[s.deleteButton,{borderColor:theme.border}]}><Text style={[s.deleteText,{color:theme.text}]}>Delete</Text></Pressable>:null}<Pressable accessibilityRole="button" accessibilityLabel="Save routine" accessibilityState={{disabled:saving||!editor.name.trim()||!editor.days.length,busy:saving}} disabled={saving||!editor.name.trim()||!editor.days.length} onPress={()=>void save()} style={[s.saveButton,{backgroundColor:theme.accent,opacity:saving||!editor.name.trim()||!editor.days.length?.4:1}]}><Text style={s.saveText}>{saving?"Scheduling…":"Save routine"}</Text></Pressable></View>
    </ScrollView>:null}</View></View></Modal>
  </Screen>;
}

const s=StyleSheet.create({intro:{gap:spacing.sm},heading:{...typography.sectionTitle,fontSize:22},body:{...typography.body},add:{minHeight:52,borderRadius:radii.md,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:spacing.sm},addText:{...typography.control,color:"#FFF"},list:{gap:spacing.md},card:{minHeight:94,borderWidth:1,borderRadius:radii.lg,padding:spacing.md,flexDirection:"row",alignItems:"center",gap:spacing.md},timeIcon:{width:48,height:48,borderRadius:24,alignItems:"center",justifyContent:"center"},cardCopy:{flex:1,gap:3},cardTitle:{fontSize:17,fontWeight:"800"},cardMeta:{fontSize:13,fontWeight:"600"},cardDocument:{fontSize:13},empty:{alignItems:"center",paddingVertical:spacing.section,gap:spacing.sm},emptyTitle:{...typography.sectionTitle},emptyBody:{fontSize:15,lineHeight:22,textAlign:"center",maxWidth:300},backdrop:{flex:1,backgroundColor:"rgba(0,0,0,.32)",justifyContent:"flex-end"},sheet:{maxHeight:"90%",borderTopLeftRadius:radii.sheet,borderTopRightRadius:radii.sheet,paddingHorizontal:spacing.xl,paddingTop:spacing.sm,paddingBottom:spacing.xl},handle:{width:38,height:4,borderRadius:2,alignSelf:"center",marginBottom:spacing.md},sheetHeader:{flexDirection:"row",alignItems:"center",justifyContent:"space-between"},sheetTitle:{...typography.sheetTitle},close:{width:controlSizes.minimumTouch,height:controlSizes.minimumTouch,alignItems:"center",justifyContent:"center"},editorContent:{paddingBottom:spacing.xl},label:{...typography.eyebrow,marginTop:spacing.md,marginBottom:spacing.sm},input:{minHeight:50,borderWidth:1,borderRadius:radii.md,paddingHorizontal:spacing.md,fontSize:16},days:{flexDirection:"row",justifyContent:"space-between",gap:spacing.xs},day:{width:39,height:42,borderWidth:1,borderRadius:20,alignItems:"center",justifyContent:"center"},dayText:{fontSize:14,fontWeight:"800"},options:{flexDirection:"row",flexWrap:"wrap",gap:spacing.sm},option:{width:"48%",flexGrow:1,minHeight:58,borderWidth:1,borderRadius:radii.md,padding:spacing.sm},optionTitle:{fontSize:14,fontWeight:"800"},optionDetail:{fontSize:12,marginTop:2},documentOptions:{gap:spacing.sm},documentOption:{minHeight:46,borderWidth:1,borderRadius:radii.md,paddingHorizontal:spacing.md,flexDirection:"row",alignItems:"center",justifyContent:"space-between"},documentOptionText:{fontSize:14,fontWeight:"600",flex:1},actions:{flexDirection:"row",gap:spacing.sm,marginTop:spacing.lg},deleteButton:{minHeight:50,borderWidth:1,borderRadius:radii.md,paddingHorizontal:spacing.xl,alignItems:"center",justifyContent:"center"},deleteText:{...typography.control},saveButton:{minHeight:50,borderRadius:radii.md,flex:1,alignItems:"center",justifyContent:"center"},saveText:{...typography.control,color:"#FFF"}});
