import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useMemo,useRef,useState } from "react";
import { ActivityIndicator,Image,KeyboardAvoidingView,Platform,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { askVotic } from "../src/api/voticApi";
import { spacing,typography } from "../src/design/tokens";
import { useDocumentLibrary } from "../src/documents/DocumentLibraryProvider";
import { useVoticTheme } from "../src/theme/ThemeProvider";

type Message={role:"user"|"votic";text:string};
export default function Assistant(){
 const {theme}=useVoticTheme();const {activeDocument}=useDocumentLibrary();
 const noteSections=useMemo(()=>activeDocument?.savedPassages?.map((passage,index)=>({heading:`Saved note ${index+1}`,text:[passage.text,passage.note.trim()?`Your note: ${passage.note.trim()}`:""].filter(Boolean).join("\n")}))||[],[activeDocument?.savedPassages]);
 const [question,setQuestion]=useState("");const [messages,setMessages]=useState<Message[]>([]);const [sending,setSending]=useState(false);const [error,setError]=useState("");const scrollRef=useRef<ScrollView>(null);
 async function send(){
  const clean=question.trim();if(!clean||sending)return;setQuestion("");setError("");setMessages(v=>[...v,{role:"user",text:clean}]);setSending(true);
  try{const document=activeDocument?{title:activeDocument.title,sections:[{heading:"Document",text:activeDocument.plainText},...noteSections]}:undefined;const answer=await askVotic(clean,document);setMessages(v=>[...v,{role:"votic",text:answer.answer}])}
  catch(e){setError(e instanceof Error?e.message:"Votic could not answer right now.")}finally{setSending(false)}
 }
 return <SafeAreaView style={[s.safe,{backgroundColor:theme.background}]}><KeyboardAvoidingView style={s.safe} behavior={Platform.OS==="ios"?"padding":undefined}>
  <View style={[s.header,{borderBottomColor:theme.border}]}><Pressable accessibilityRole="button" accessibilityLabel="Close Ask Votic" onPress={()=>router.back()} style={s.icon}><Ionicons name="chevron-down" size={27} color={theme.text}/></Pressable><View style={s.headerCopy}><Text style={[s.title,{color:theme.text}]}>Ask Votic</Text><Text numberOfLines={1} style={[s.context,{color:theme.mutedText}]}>{activeDocument?"About "+activeDocument.title:"Votic help"}</Text></View><View style={s.icon}/></View>
  <ScrollView ref={scrollRef} contentContainerStyle={s.messages} keyboardShouldPersistTaps="handled" onContentSizeChange={()=>scrollRef.current?.scrollToEnd({animated:true})}>
   {messages.length===0?<View style={s.welcome}><Image source={require("../assets/empty-states/ask-votic.png")} resizeMode="contain" accessible accessibilityRole="image" accessibilityLabel="A document with an Ask Votic conversation bubble" style={s.welcomeImage}/><Text style={[s.welcomeTitle,{color:theme.text}]}>What would you like to understand?</Text><Text style={[s.body,{color:theme.mutedText}]}>{activeDocument?"Ask about this document, your saved passages, or your notes.":"Ask a question about using Votic."}</Text>{activeDocument&&noteSections.length?<View style={s.suggestions}><Pressable accessibilityRole="button" onPress={()=>setQuestion("Summarize my notes from this document.")} style={[s.suggestion,{borderColor:theme.border}]}><Text style={[s.suggestionText,{color:theme.text}]}>Summarize my notes</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>setQuestion("Quiz me on my notes from this document.")} style={[s.suggestion,{borderColor:theme.border}]}><Text style={[s.suggestionText,{color:theme.text}]}>Quiz me on my notes</Text></Pressable><Pressable accessibilityRole="button" onPress={()=>setQuestion("Explain the ideas in my saved notes from this document.")} style={[s.suggestion,{borderColor:theme.border}]}><Text style={[s.suggestionText,{color:theme.text}]}>Explain my notes</Text></Pressable></View>:null}</View>:messages.map((m,i)=><View key={i} style={[s.message,m.role==="user"?s.userMessage:s.voticMessage,m.role==="user"&&{backgroundColor:theme.surfaceMuted}]}><Text style={[s.body,{color:theme.text}]}>{m.text}</Text></View>)}
   {sending?<View accessibilityLiveRegion="polite" style={s.thinking}><ActivityIndicator color={theme.accent}/><Text style={[s.status,{color:theme.mutedText}]}>Thinking about your question…</Text></View>:null}
   {error?<View accessibilityLiveRegion="polite" style={[s.error,{borderColor:theme.border}]}><Text style={[s.body,{color:theme.text}]}>{error}</Text><Pressable accessibilityRole="button" accessibilityLabel="Retry question" disabled={sending} onPress={()=>void send()} style={s.retry}><Ionicons name="refresh" size={18} color={theme.accent}/><Text style={[s.retryText,{color:theme.accent}]}>Try again</Text></Pressable></View>:null}
  </ScrollView>
  <View style={[s.composer,{borderTopColor:theme.border,backgroundColor:theme.background}]}><TextInput accessibilityLabel="Ask Votic a question" value={question} onChangeText={setQuestion} placeholder={activeDocument?"Ask about this document":"Ask Votic"} placeholderTextColor={theme.mutedText} multiline maxLength={1000} style={[s.input,{color:theme.text,backgroundColor:theme.surfaceMuted}]} onSubmitEditing={()=>void send()}/><Pressable accessibilityRole="button" accessibilityLabel="Send question" disabled={!question.trim()||sending} onPress={()=>void send()} style={[s.send,{backgroundColor:theme.accent,opacity:!question.trim()||sending?.4:1}]}><Ionicons name="arrow-up" size={22} color="#FFF"/></Pressable></View>
 </KeyboardAvoidingView></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1},header:{minHeight:68,borderBottomWidth:1,flexDirection:"row",alignItems:"center",paddingHorizontal:spacing.md},icon:{width:48,height:48,alignItems:"center",justifyContent:"center"},headerCopy:{flex:1,alignItems:"center"},title:{...typography.sectionTitle},context:{fontSize:12,maxWidth:"90%"},messages:{padding:spacing.xl,gap:spacing.lg,flexGrow:1},welcome:{marginTop:spacing.lg,gap:spacing.sm},welcomeImage:{width:"100%",maxWidth:260,aspectRatio:1,alignSelf:"center",marginBottom:spacing.sm},welcomeTitle:{...typography.screenTitle,fontSize:26},body:{...typography.body},message:{maxWidth:"92%",paddingVertical:spacing.sm},userMessage:{alignSelf:"flex-end",borderRadius:16,paddingHorizontal:spacing.md},voticMessage:{alignSelf:"flex-start"},thinking:{flexDirection:"row",alignItems:"center",gap:spacing.sm},status:{fontSize:14},error:{borderWidth:1,borderRadius:12,padding:spacing.md,gap:spacing.sm},retry:{minHeight:48,alignSelf:"flex-start",flexDirection:"row",alignItems:"center",gap:spacing.sm},retryText:{...typography.control},suggestions:{gap:spacing.sm,marginTop:spacing.md},suggestion:{minHeight:46,borderWidth:1,borderRadius:16,paddingHorizontal:spacing.md,justifyContent:"center"},suggestionText:{fontSize:14,fontWeight:"700"},composer:{borderTopWidth:1,padding:spacing.md,flexDirection:"row",alignItems:"flex-end",gap:spacing.sm},input:{flex:1,minHeight:48,maxHeight:120,borderRadius:18,paddingHorizontal:spacing.lg,paddingVertical:12,fontSize:16},send:{width:48,height:48,borderRadius:24,alignItems:"center",justifyContent:"center"}});
