import { Ionicons } from "@expo/vector-icons";
import { router } from "expo-router";
import { useRef,useState } from "react";
import { ActivityIndicator,Animated,Easing,Image,KeyboardAvoidingView,Platform,Pressable,ScrollView,StyleSheet,Text,TextInput,View } from "react-native";
import { SafeAreaView } from "react-native-safe-area-context";
import { askVotic } from "../src/api/voticApi";
import { spacing,typography } from "../src/design/tokens";
import { useDocumentLibrary } from "../src/documents/DocumentLibraryProvider";
import { useVoticTheme } from "../src/theme/ThemeProvider";
import { VoticLogo } from "../src/components/VoticLogo";
import { useAccessibilityPreferences } from "../src/accessibility/AccessibilityProvider";

type Message={role:"user"|"votic";text:string};
type PromptFlight={label:string;x:number;y:number;dx:number;dy:number};
export function AskVotic({embedded=false}:{embedded?:boolean}){
 const {theme}=useVoticTheme();const {activeDocument}=useDocumentLibrary();
 const {reduceMotion}=useAccessibilityPreferences();
 const [question,setQuestion]=useState("");const [messages,setMessages]=useState<Message[]>([]);const [sending,setSending]=useState(false);const [error,setError]=useState("");const scrollRef=useRef<ScrollView>(null);
 const [flight,setFlight]=useState<PromptFlight|null>(null);const rootRef=useRef<View>(null);const composerTargetRef=useRef<View>(null);const promptRefs=useRef<Record<string,View|null>>({});
 const promptEntry=useRef(new Animated.Value(1)).current;const sendBounce=useRef(new Animated.Value(0)).current;const flightProgress=useRef(new Animated.Value(0)).current;
 function settlePrompt(label:string){setQuestion(label);promptEntry.setValue(0);sendBounce.setValue(0);Animated.parallel([Animated.timing(promptEntry,{toValue:1,duration:240,easing:Easing.out(Easing.cubic),useNativeDriver:true}),Animated.sequence([Animated.timing(sendBounce,{toValue:8,duration:120,easing:Easing.in(Easing.quad),useNativeDriver:true}),Animated.spring(sendBounce,{toValue:0,damping:7,stiffness:210,mass:.65,useNativeDriver:true})])]).start();}
 function choosePrompt(label:string){
  if(reduceMotion){setQuestion(label);return;}const source=promptRefs.current[label];const target=composerTargetRef.current;const root=rootRef.current;if(!source||!target||!root){settlePrompt(label);return;}
  root.measureInWindow((rootX,rootY)=>source.measureInWindow((sourceX,sourceY,_sourceWidth,sourceHeight)=>target.measureInWindow((targetX,targetY)=>{const x=sourceX-rootX+12;const y=sourceY-rootY+sourceHeight/2-18;setFlight({label,x,y,dx:targetX-rootX+16-x,dy:targetY-rootY+8-y});flightProgress.setValue(0);requestAnimationFrame(()=>Animated.timing(flightProgress,{toValue:1,duration:820,easing:Easing.inOut(Easing.cubic),useNativeDriver:true}).start(()=>{setFlight(null);settlePrompt(label);}));})));
 }
 async function send(){
  const clean=question.trim();if(!clean||sending)return;setQuestion("");setError("");setMessages(v=>[...v,{role:"user",text:clean}]);setSending(true);
  try{const document=activeDocument?{title:activeDocument.title,sections:[{heading:"Document",text:activeDocument.plainText}]}:undefined;const answer=await askVotic(clean,document);setMessages(v=>[...v,{role:"votic",text:answer.answer}])}
  catch(e){setError(e instanceof Error?e.message:"Votic could not answer right now.")}finally{setSending(false)}
 }
 return <SafeAreaView edges={embedded?["top","left","right"]:["top","bottom","left","right"]} style={[s.safe,{backgroundColor:theme.background}]}><KeyboardAvoidingView style={s.safe} behavior={Platform.OS==="ios"?"padding":undefined}><View ref={rootRef} style={s.safe}>
  <View style={[s.header,{borderBottomColor:theme.border}]}>{embedded?<VoticLogo compact/>:<Pressable accessibilityRole="button" accessibilityLabel="Close Ask Votic" onPress={()=>router.back()} style={s.icon}><Ionicons name="chevron-down" size={27} color={theme.text}/></Pressable>}<View style={s.headerCopy}><Text style={[s.title,{color:theme.text}]}>Ask Votic</Text><Text numberOfLines={1} style={[s.context,{color:theme.mutedText}]}>{activeDocument?"About "+activeDocument.title:"Reading and document help"}</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Search conversations" style={s.icon}><Ionicons name="search" size={22} color={theme.text}/></Pressable></View>
  <ScrollView ref={scrollRef} contentContainerStyle={s.messages} keyboardShouldPersistTaps="handled" onContentSizeChange={()=>scrollRef.current?.scrollToEnd({animated:true})}>
   {messages.length===0?<View style={s.welcome}><Image accessibilityLabel="Votic looking through a magnifying glass" source={require("../assets/votic-search-mascot.png")} resizeMode="contain" style={s.searchMascot}/><Text style={[s.welcomeTitle,{color:theme.text}]}>What can I help you with?</Text><Text style={[s.body,s.welcomeBody,{color:theme.mutedText}]}>{activeDocument?"Ask about this document, clarify a passage, or find an idea you heard.":"Open a document or ask a question about reading with Votic."}</Text><View style={s.prompts}>{["Summarize this document","Explain this section","Quiz me on this document","Help with my notes","Compare key ideas","Find information"].map((label,i)=><Pressable ref={node=>{promptRefs.current[label]=node;}} key={label} onPress={()=>choosePrompt(label)} style={({pressed})=>[s.prompt,{backgroundColor:theme.surfaceMuted,opacity:pressed?.68:1}]}><Ionicons name={i===0?"sparkles-outline":i===1?"bulb-outline":i===2?"school-outline":"search-outline"} size={17} color={theme.accent}/><Text style={[s.promptText,{color:theme.accent}]}>{label}</Text></Pressable>)}</View></View>:messages.map((m,i)=><View key={i} style={[s.message,m.role==="user"?s.userMessage:s.voticMessage,m.role==="user"&&{backgroundColor:theme.accent}]}><Text style={[s.body,{color:m.role==="user"?"#FFF":theme.text}]}>{m.text}</Text></View>)}
   {sending?<View accessibilityLiveRegion="polite" style={s.thinking}><ActivityIndicator color={theme.accent}/><Text style={[s.status,{color:theme.mutedText}]}>Thinking about your question…</Text></View>:null}
   {error?<View accessibilityLiveRegion="polite" style={[s.error,{borderColor:theme.border}]}><Text style={[s.body,{color:theme.text}]}>{error}</Text><Pressable accessibilityRole="button" accessibilityLabel="Retry question" disabled={sending} onPress={()=>void send()} style={s.retry}><Ionicons name="refresh" size={18} color={theme.accent}/><Text style={[s.retryText,{color:theme.accent}]}>Try again</Text></Pressable></View>:null}
  </ScrollView>
  <View style={[s.composer,{borderTopColor:theme.border,backgroundColor:theme.background}]}><View ref={composerTargetRef} style={s.inputMotion}><Animated.View style={{opacity:promptEntry,transform:[{translateY:promptEntry.interpolate({inputRange:[0,1],outputRange:[-8,0]})}]}}><TextInput accessibilityLabel="Ask Votic a question" value={question} onChangeText={setQuestion} placeholder={activeDocument?"Ask about this document":"Ask Votic"} placeholderTextColor={theme.mutedText} multiline maxLength={1000} style={[s.input,{color:theme.text,backgroundColor:theme.surfaceMuted}]} onSubmitEditing={()=>void send()}/></Animated.View></View><Animated.View style={{transform:[{translateY:sendBounce}]}}><Pressable accessibilityRole="button" accessibilityLabel="Send question" disabled={!question.trim()||sending} onPress={()=>void send()} style={[s.send,{backgroundColor:theme.accent,opacity:!question.trim()||sending?.4:1}]}><Ionicons name="arrow-up" size={22} color="#FFF"/></Pressable></Animated.View></View>
  {flight?<Animated.View pointerEvents="none" style={[s.flightChip,{left:flight.x,top:flight.y,backgroundColor:theme.surfaceMuted,opacity:flightProgress.interpolate({inputRange:[0,.82,1],outputRange:[1,1,.15]}),transform:[{translateX:flightProgress.interpolate({inputRange:[0,.28,.58,1],outputRange:[0,18,-10,flight.dx]})},{translateY:flightProgress.interpolate({inputRange:[0,.28,.58,1],outputRange:[0,flight.dy*.28,flight.dy*.62,flight.dy]})},{rotate:flightProgress.interpolate({inputRange:[0,.3,.62,1],outputRange:["0deg","3deg","-2deg","0deg"]})},{scale:flightProgress.interpolate({inputRange:[0,.7,1],outputRange:[1,.94,.88]})}]}]}><Ionicons name="sparkles-outline" size={15} color={theme.accent}/><Text numberOfLines={1} style={[s.flightText,{color:theme.accent}]}>{flight.label}</Text></Animated.View>:null}
 </View></KeyboardAvoidingView></SafeAreaView>
}
export default function Assistant(){return <AskVotic/>;}
const s=StyleSheet.create({safe:{flex:1},header:{minHeight:68,borderBottomWidth:1,flexDirection:"row",alignItems:"center",paddingHorizontal:spacing.lg,gap:spacing.sm},icon:{width:48,height:48,alignItems:"center",justifyContent:"center"},headerCopy:{flex:1,alignItems:"center"},title:{...typography.sectionTitle},context:{fontSize:12,maxWidth:"90%"},messages:{padding:spacing.xl,gap:spacing.lg,flexGrow:1},welcome:{marginTop:spacing.md,gap:spacing.sm,alignItems:"center"},searchMascot:{width:150,height:126,marginBottom:spacing.sm},welcomeTitle:{...typography.screenTitle,fontSize:26,textAlign:"center"},welcomeBody:{textAlign:"center"},prompts:{width:"100%",gap:8,marginTop:12},prompt:{minHeight:44,borderRadius:14,paddingHorizontal:16,flexDirection:"row",alignItems:"center",gap:10},promptText:{fontSize:15,fontWeight:"600"},body:{...typography.body},message:{maxWidth:"92%",paddingVertical:spacing.sm},userMessage:{alignSelf:"flex-end",borderRadius:16,paddingHorizontal:spacing.md},voticMessage:{alignSelf:"flex-start"},thinking:{flexDirection:"row",alignItems:"center",gap:spacing.sm},status:{fontSize:14},error:{borderWidth:1,borderRadius:12,padding:spacing.md,gap:spacing.sm},retry:{minHeight:48,alignSelf:"flex-start",flexDirection:"row",alignItems:"center",gap:spacing.sm},retryText:{...typography.control},composer:{borderTopWidth:1,padding:spacing.md,flexDirection:"row",alignItems:"flex-end",gap:spacing.sm},inputMotion:{flex:1},input:{width:"100%",minHeight:48,maxHeight:120,borderRadius:18,paddingHorizontal:spacing.lg,paddingVertical:12,fontSize:16},send:{width:48,height:48,borderRadius:24,alignItems:"center",justifyContent:"center"},flightChip:{position:"absolute",zIndex:20,maxWidth:230,minHeight:36,borderRadius:14,paddingHorizontal:12,flexDirection:"row",alignItems:"center",gap:7,elevation:8,shadowColor:"#000",shadowOpacity:.18,shadowRadius:8,shadowOffset:{width:0,height:3}},flightText:{fontSize:13,fontWeight:"700",maxWidth:190}});
