import { createContext,PropsWithChildren,useContext,useEffect,useMemo,useState } from "react";import { VoticDocument } from "./types";import { loadDocuments,saveDocuments } from "./documentStorage";
type Library={documents:VoticDocument[];activeDocument:VoticDocument|null;addTextDocument:(sourceName:string,text:string)=>VoticDocument;openDocument:(id:string)=>void;updateProgress:(id:string,progress:number,sentenceIndex?:number,wordIndex?:number)=>void;recordActivity:(id:string,readingSeconds:number,listeningSeconds:number)=>void;completeDocument:(id:string,sentenceIndex:number,wordIndex:number)=>void;updatePlaybackRate:(id:string,rate:number)=>void;updateWorksheetResponses:(id:string,responses:Record<string,string|boolean>)=>void};
const C=createContext<Library|null>(null);
function titleFrom(sourceName:string,text:string){const fileTitle=sourceName.replace(/\.(txt|md)$/i,"").trim();const first=text.split(/\r?\n/).map(v=>v.trim()).find(Boolean)?.replace(/^#+\s*/,"").slice(0,80);return fileTitle||first||"Untitled document"}
export function DocumentLibraryProvider({children}:PropsWithChildren){const [documents,setDocuments]=useState<VoticDocument[]>([]);const [activeId,setActiveId]=useState<string|null>(null);const [hydrated,setHydrated]=useState(false);useEffect(()=>{let mounted=true;loadDocuments().then(saved=>{if(!mounted)return;setDocuments(saved);setActiveId(saved[0]?.id||null);setHydrated(true)});return()=>{mounted=false}},[]);useEffect(()=>{if(hydrated)saveDocuments(documents).catch(()=>{})},[documents,hydrated]);const activeDocument=useMemo(()=>documents.find(d=>d.id===activeId)||null,[documents,activeId]);
function addTextDocument(sourceName:string,text:string){const now=Date.now();const doc:VoticDocument={id:"doc-"+now+"-"+Math.random().toString(36).slice(2,8),title:titleFrom(sourceName,text),sourceName,plainText:text.trim(),importedAt:now,updatedAt:now,lastOpenedAt:now,progress:0,sentenceIndex:0,wordIndex:0,playbackRate:1,activity:{},worksheetResponses:{}};setDocuments(current=>[doc,...current]);setActiveId(doc.id);return doc}
function openDocument(id:string){setActiveId(id);setDocuments(current=>current.map(document=>document.id===id?{...document,lastOpenedAt:Date.now()}:document))}
function updateProgress(id:string,progress:number,sentenceIndex=0,wordIndex=0){setDocuments(current=>current.map(d=>d.id===id?{...d,progress:Math.max(0,Math.min(1,progress)),sentenceIndex,wordIndex,updatedAt:Date.now()}:d))}function updatePlaybackRate(id:string,rate:number){setDocuments(current=>current.map(d=>d.id===id?{...d,playbackRate:rate,updatedAt:Date.now()}:d))}function updateWorksheetResponses(id:string,responses:Record<string,string|boolean>){setDocuments(current=>current.map(d=>d.id===id?{...d,worksheetResponses:responses,updatedAt:Date.now()}:d))}
function recordActivity(id:string,readingSeconds:number,listeningSeconds:number){const now=new Date();const day=[now.getFullYear(),String(now.getMonth()+1).padStart(2,"0"),String(now.getDate()).padStart(2,"0")].join("-");setDocuments(current=>current.map(document=>{if(document.id!==id)return document;const previous=document.activity?.[day]||{readingSeconds:0,listeningSeconds:0};return {...document,activity:{...document.activity,[day]:{readingSeconds:previous.readingSeconds+readingSeconds,listeningSeconds:previous.listeningSeconds+listeningSeconds}}}}))}
function completeDocument(id:string,sentenceIndex:number,wordIndex:number){const now=Date.now();setDocuments(current=>current.map(document=>document.id===id?{...document,progress:1,sentenceIndex,wordIndex,completedAt:document.completedAt||now,updatedAt:now}:document))}
return <C.Provider value={{documents,activeDocument,addTextDocument,openDocument,updateProgress,recordActivity,completeDocument,updatePlaybackRate,updateWorksheetResponses}}>{children}</C.Provider>}
export function useDocumentLibrary(){const c=useContext(C);if(!c)throw new Error("useDocumentLibrary must be used inside DocumentLibraryProvider");return c}
